### ISSUE TITLE
User cheatsheets support

### ISSUE THREAD

**Issue by Shura1oplot** [vrachieru/cheatsheet#1]
Please add support of cheatsheets located in `User\cheatsheets` directory. Thank you!

**Comment by vrachieru** [comment]
Hei there @Shura1oplot,

I've just added support for user cheatsheets and released [v1.0.2](../releases/tag/v1.0.2) which should be available soon on [Package Control](https://packagecontrol.io/packages/Cheatsheet).
Just place your cheatsheets in `~/.cheatsheet` and restart Sublime or call the `Refresh local database` command.
Try it out and tell me what you think :)

**Comment by Shura1oplot** [comment]
@vrachieru Thank you! But could you use `Packages/User/cheatsheets` instead of `~/.cheatsheet`? This is a default directory for user's customizations for Sublime Text. Next point, `os.symlink` is not available on Windows, instead of it you can just write your command file into `Packages/User/LocalCheatsheet.sublime-commands`.

**Comment by Ghos3t** [comment]
Correct me if I'm wrong but isn't giving paths like this- ~/.cheatsheet a UNIX thing. I don't understand what the correct path is for Windows operating system. Can you please add the path to be used for user cheatsheets in Windows. I've tried the following paths with no success:

C:\Users\My_UserName\cheatsheet
C:\Users\My_UserName\AppData\Roaming\Sublime Text 3\Packages\Cheatsheet\database
C:\Users\My_UserName\AppData\Roaming\Sublime Text 3\Packages\Cheatsheet\database\local
