### ISSUE TITLE
For Cuda

### ISSUE THREAD

**Issue by Alexey-T** [vrachieru/cheatsheet#2]
Hi; Can i port addon to Cudatext? I need your sheet-files. as is. So can i take em?
2. Do u think it's ok to place sheets in one level folder (not nesteed dirs).

**Comment by vrachieru** [comment]
Hi @Alexey-T, 
You can port the cheatsheets as long as you credit me (this repo).
As for having them in a single folder.. it's not a problem. The current hierarchy is just for organizational purpouses.
